name: Desktop 构建

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-windows:
    runs-on: windows-latest
    name: 构建 Windows 桌面版本

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 构建 Windows 程序
        run: |
          .\gradlew.bat :composeApp:packageDistributionForCurrentOS
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          KEYSTORE_PASSWORD: "dummy_password"
          KEYSTORE_ALIAS: "dummy_alias"
          KEY_PASSWORD: "dummy_password"
          KEYSTORE_PATH: "gradle.properties"

      - name: 上传 Windows 安装包 (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: Traclock-Windows-EXE-Installer
          # 根据你的日志，文件就在这个 msi 文件夹里
          path: composeApp/build/compose/binaries/main/exe/*.exe
          retention-days: 7

      - name: 上传免安装版 (如果存在)
        uses: actions/upload-artifact@v4
        with:
          name: Traclock-Windows-Portable
          path: composeApp/build/compose/binaries/main/app/
          if-no-files-found: ignore
          retention-days: 7
